version: '3.8'

services:
  relayer-smtp:
    build:
      context: .
      dockerfile: SMTP.Dockerfile
    container_name: relayer-smtp
    ports:
      - "3000:3000"
    env_file:
      - .env

  relayer-imap:
    build:
      context: .
      dockerfile: IMAP.Dockerfile
    container_name: relayer-imap
    ports:
      - "3001:3001"
    env_file:
      - .env

  relayer:
    build:
      context: .
      dockerfile: Relayer.Dockerfile
    container_name: relayer
    ports:
      - "4500:4500"
    env_file:
      - .env